[supervisord]
nodaemon=true

[program:mysqld]
command=/etc/init.d/mariadb start

[program:activemq]
command=/opt/activemq/bin/activemq start

[program:voj-web]
command=bash -c 'sleep 15 && java -jar /opt/voj/voj.web.jar'
directory=/opt/voj

